### ISSUE TITLE
TestCase 10 : delete-everything-openshift does not delete Prometheus secrets

### ISSUE THREAD

**Issue by deleeuwblue** [IBM/operator-sample-go#92]
**Issue:**
The script code for deleting these secrets is not correct: 

prometheus-token-secret
prometheus-cert-secret

The script does this:

    oc delete --force secret prometheus-token-secret -n openshift-operators
    oc delete --force secret prometheus-token-secret -n application-beta
    oc get secret prometheus-token-secret -n openshift-operators
    oc get secret prometheus-token-secret -n application-beta

but it should do something like this:

    oc delete --force secret prometheus-cert-secret -n application-beta
    oc delete --force secret prometheus-token-secret -n application-beta
    oc get secret prometheus-cert-secret -n application-beta
    oc get secret prometheus-token-secret -n application-beta

**Link to the documentation:**

**Comment by thomassuedbroecker** [comment]
@deleeuwblue The issue is fixed in this commit: https://github.com/IBM/operator-sample-go/commit/0e79f48f2dd4c64e079acbb27d543c028837e5a5 is also related to this issue create the secret https://github.com/IBM/operator-sample-go/issues/86

**Comment by deleeuwblue** [comment]
@thomassuedbroecker The commit https://github.com/IBM/operator-sample-go/commit/0e79f48f2dd4c64e079acbb27d543c028837e5a5 still does not delete the secret:

prometheus-cert-secret

**Comment by thomassuedbroecker** [comment]
Thanks https://github.com/IBM/operator-sample-go/commit/37a596c508e93dc2af85a9d87dc49577038a67f0

**Comment by deleeuwblue** [comment]
Fixed
